### ISSUE TITLE
is there a way to get the current playing track # or track title?

### ISSUE THREAD

**Issue by steverethink** [webbestmaster/react-audio-player-pro#1]
I was hoping to show the current playing track # and/or title elsewhere on a website while using this player.

I'm using the `<AudioPlayer/>` example in the documentation with the tracklist stored in 'audioTrackList'.
I can do this: 

```javascript
let TrackNames = Object.values(audioTrackList); // just grab all values from the track list
console.log(TrackNames[0].mediaMetadata.title); // spit out the title of the first track [0]
```
i'm wondering how i can get the current active track # so i can do:
```javascript
TrackNames[activeTrackNumber].mediaMetadata.title
```

Thanks for any info!

**Comment by webbestmaster** [comment]
Hi, 
to get current track's title you can use smth like this

```
navigator.mediaSession.metadata && navigator.mediaSession.metadata.title
```
